global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheusJob'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9090'] #Servidor prometheus
  - job_name: 'transaction-bff'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] #Servidor da minha aplicação