

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: br.com.mdrapalski.transactionbff.api

spring:
  kafka:
    producer:
      client-id: transaction-bbf
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: transaction-bbf
      group-id: transaction-bbf
    bootstrap-servers: localhost:9092
    properties:
      spring:
        json:
          trusted:
            packages: br.com.mdrapalski.*

  redis:
    port: 6379
    host: localhost

url:
  limits: http://localhost:3000
  transactions: http://localhost:3001

app:
  topic: transaction