spring:
  data:
    mongodb:
      url: mongodb://admin:admin@localhost:27017/transaction
      database: transaction
server:
  port: 3001

management:
  endpoints:
    web:
      exposure:
        include: health, beans