spring:
  kafka:
    consumer:
      client-id: transaction-svc
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: limits-svc
      auto-offset-reset: latest
      enable-auto-commit: false
      group-id: transaction-svc
    bootstrap-servers: localhost:9092

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, beans

app:
  topic: transaction
  returnTopic: reversed-transaction